name: portfolio
description: Portfolio web page.
publish_to: none

# Version: MAJOR.MINOR.PATCH+BUILD_NUMBER
# This is the single source of truth for the app version
version: 1.0.0+1

# Environment constraints
# This specifies the Dart SDK version (not Flutter version)
# Flutter 3.38.4 includes Dart 3.10.3
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  url_launcher: ^6.3.1
  flutter_bloc: ^9.1.1
  cached_network_image: ^3.2.0
  provider: ^6.1.5
  auto_size_text: ^3.0.0
  firebase_core: ^4.2.1
  firebase_database: ^12.1.0
  firebase_auth: ^6.1.2
  bloc: ^9.1.0
  get_it: ^9.2.0
  equatable: ^2.0.7
  rxdart: ^0.28.0
  sqflite: ^2.3.0
  path: ^1.8.3
  flutter_dotenv: ^6.0.0
  go_router: ^14.7.0
  shared_preferences: ^2.3.3
  flutter_web_plugins:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/img/avatar.jpg
    - assets/img/default.png
    - assets/img/development.jpg
    - assets/icons/android.png
    - assets/icons/blog.png
    - assets/icons/contact.png
    - assets/icons/facebook.png
    - assets/icons/features.png
    - assets/icons/flutter.png
    - assets/icons/github.png
    - assets/icons/home.png
    - assets/icons/kmp.png
    - assets/icons/linkedin.png
    - assets/icons/medium.png
    - assets/icons/portfolio.png
    - assets/icons/resume.png
    - assets/icons/twitter.png
    - assets/projects/cashplus.jpg
    - assets/projects/daimler-app.png
    - assets/projects/loro-retail.jpeg
    - assets/projects/loro-sst.jpeg
    - assets/projects/mechanic-advisor.jpg
    - assets/projects/medically-home.png
    - assets/projects/minimed.jpg
    - assets/projects/sbb-app.jpg
    - assets/projects/sumex.png
    - assets/projects/unlimited-biking.jpg
    - assets/certificates/coursera-kotlin.jpeg
    - assets/certificates/java-data-structures.jpg
    - assets/certificates/jetpack-compose.jpg
    - assets/certificates/kotlin-coroutines.jpg
    - assets/certificates/mastering-system-design-interview.jpg
    - assets/certificates/software-architecture.jpg
  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat/Montserrat-Thin.ttf
          weight: 100
        - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: fonts/montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: fonts/montserrat/Montserrat-Regular.ttf
          weight: 400
        - asset: fonts/montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: fonts/montserrat/Montserrat-SemiBold.ttf
          weight: 600
        - asset: fonts/montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
          weight: 800
