name: portfolio
description: Portfolio web page.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  animated_text_kit: ^4.2.2
  url_launcher: ^6.3.1
  flutter_bloc: ^8.1.6
  cached_network_image: ^3.2.0
  provider: ^6.1.5
  auto_size_text: ^3.0.0
  firebase_core: ^3.13.0
  firebase_database: ^11.3.5
  bloc: ^8.1.4
  get_it: ^8.0.3
  equatable: ^2.0.7
  rxdart: ^0.28.0
  sqflite: ^2.3.0
  path: ^1.8.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/img/avatar.jpg
  - assets/img/android.png
  - assets/img/flutter.png
  - assets/img/kmp.png
  - assets/img/home.png
  - assets/img/blog.png
  - assets/img/features.png
  - assets/img/portfolio.png
  - assets/img/resume.png
  - assets/img/contact.png
  - assets/img/linkedin.png
  - assets/img/github.png
  - assets/img/medium.png
  - assets/img/sbb-app.jpg
  - assets/img/sumex.png
  - assets/img/medically-home.png
  - assets/img/cashplus.jpg
  - assets/img/minimed.jpg
  - assets/img/mechanic-advisor.jpg
  - assets/img/unlimited-biking.jpg
  - assets/img/daimler-app.png
  - assets/img/development.jpg
  - assets/img/loro-sst.jpeg
  - assets/img/loro-retail.jpeg
  - assets/certificates/coursera_kotlin.jpeg
  - assets/certificates/java_data_structures.jpg
  - assets/certificates/jetpack_compose.jpg
  - assets/certificates/kotlin_coroutines.jpg
  - assets/certificates/mastering_system_design_interview.jpg
  - assets/certificates/software_architecture.jpg
  fonts:
  - family: Montserrat
    fonts:
    - asset: fonts/montserrat/Montserrat-Thin.ttf
      weight: 100
    - asset: fonts/montserrat/Montserrat-ExtraLight.ttf
      weight: 200
    - asset: fonts/montserrat/Montserrat-Light.ttf
      weight: 300
    - asset: fonts/montserrat/Montserrat-Regular.ttf
      weight: 400
    - asset: fonts/montserrat/Montserrat-Medium.ttf
      weight: 500
    - asset: fonts/montserrat/Montserrat-SemiBold.ttf
      weight: 600
    - asset: fonts/montserrat/Montserrat-Bold.ttf
      weight: 700
    - asset: fonts/montserrat/Montserrat-ExtraBold.ttf
      weight: 800
